/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.eletronlivre.jdevbot.gui;

import br.com.eletronlivre.jdevbot.DevBotSerial;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vsenger
 */
public class DevBotWindow extends javax.swing.JFrame {

  DecimalFormat formatadorTemperatura = new DecimalFormat("##.00");
  String comandoAtual;
  boolean updater;
  DevBotSerial robot;
  Collection<DevBotSerial> robots = new ArrayList<DevBotSerial>();

  /**
   * Creates new form DevBotConsole
   */
  public DevBotWindow() {
    initComponents();

  }

  public DevBotWindow(DevBotSerial robot, Collection<DevBotSerial> robots) {
    initComponents();
    this.robot = robot;
    this.robots = robots;
  }

  public void executar() {
    try {
      if (todosRobots.isSelected()) {
        for (DevBotSerial r : robots) {
          r.send(comandoAtual + "?" + intensidade.getValue());
        }
      } else {
        robot.send(comandoAtual + "?" + intensidade.getValue());
      }
    } catch (IOException ex) {
      Logger.getLogger(DevBotWindow.class.getName()).log(Level.SEVERE, null, ex);
    }

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botaoDireita = new javax.swing.JButton();
        botaoFrente = new javax.swing.JButton();
        botaoParar = new javax.swing.JButton();
        botaoRe = new javax.swing.JButton();
        botaoEsquerda = new javax.swing.JButton();
        girarHorario = new javax.swing.JButton();
        girarAntiHorario = new javax.swing.JButton();
        botaoEsquerda1 = new javax.swing.JButton();
        botaoDireita1 = new javax.swing.JButton();
        intensidade = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sensorLuz = new javax.swing.JTextField();
        botaoAtualizar = new javax.swing.JButton();
        tempoSensorLuz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sliderSensorLuz = new javax.swing.JSlider();
        painelSensorLuz = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        temperatura = new javax.swing.JLabel();
        distancia = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        sliderServo = new javax.swing.JSlider();
        botaoServo = new javax.swing.JButton();
        todosRobots = new javax.swing.JToggleButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoDireita.setText("Direita");
        botaoDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDireitaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoDireita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 78, -1));

        botaoFrente.setText("Frente");
        botaoFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFrenteActionPerformed(evt);
            }
        });
        jPanel1.add(botaoFrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 78, -1));

        botaoParar.setText("Parar");
        botaoParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPararActionPerformed(evt);
            }
        });
        jPanel1.add(botaoParar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 78, -1));

        botaoRe.setText("Ré");
        botaoRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoReActionPerformed(evt);
            }
        });
        jPanel1.add(botaoRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 78, -1));

        botaoEsquerda.setText("Esquerda");
        botaoEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEsquerdaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoEsquerda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        girarHorario.setText("Girar");
        girarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girarHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(girarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 78, -1));

        girarAntiHorario.setText("Girar");
        girarAntiHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girarAntiHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(girarAntiHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 78, -1));

        botaoEsquerda1.setText("Esquerda");
        botaoEsquerda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEsquerda1ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoEsquerda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        botaoDireita1.setText("Direita");
        botaoDireita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDireita1ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoDireita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 78, -1));

        intensidade.setMaximum(4);

        jLabel2.setText("Intensidade");

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setText("Sensor Luz");

        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        tempoSensorLuz.setText("0");

        jLabel4.setText("vezes por segundo");

        sliderSensorLuz.setMaximum(1023);

        javax.swing.GroupLayout painelSensorLuzLayout = new javax.swing.GroupLayout(painelSensorLuz);
        painelSensorLuz.setLayout(painelSensorLuzLayout);
        painelSensorLuzLayout.setHorizontalGroup(
            painelSensorLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        painelSensorLuzLayout.setVerticalGroup(
            painelSensorLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        temperatura.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        temperatura.setText("0 c");

        distancia.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        distancia.setText("0 c");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distancia)
                    .addComponent(temperatura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(temperatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(distancia)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderSensorLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sensorLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(botaoAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tempoSensorLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(painelSensorLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sensorLuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderSensorLuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelSensorLuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAtualizar)
                    .addComponent(tempoSensorLuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jLabel5.setText("Servo-motor");

        sliderServo.setMaximum(175);
        sliderServo.setMinimum(1);
        sliderServo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderServoStateChanged(evt);
            }
        });

        botaoServo.setText("Configurar!");
        botaoServo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoServoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(sliderServo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoServo))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderServo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoServo)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        todosRobots.setText("Mandar para todos robots");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                        .addComponent(intensidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2)
                    .addComponent(todosRobots))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intensidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(todosRobots))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void botaoFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFrenteActionPerformed
    comandoAtual = "frente";
    executar();

  }//GEN-LAST:event_botaoFrenteActionPerformed

  private void botaoReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoReActionPerformed
    comandoAtual = "re";
    executar();
  }//GEN-LAST:event_botaoReActionPerformed

  private void botaoPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPararActionPerformed
    comandoAtual = "parar";
    executar();

  }//GEN-LAST:event_botaoPararActionPerformed

  private void botaoEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEsquerdaActionPerformed
    comandoAtual = "esquerda";
    executar();
  }//GEN-LAST:event_botaoEsquerdaActionPerformed

  private void botaoEsquerda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEsquerda1ActionPerformed
    comandoAtual = "re";
    executar();

  }//GEN-LAST:event_botaoEsquerda1ActionPerformed

  private void girarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girarHorarioActionPerformed
    comandoAtual = "gh";
    executar();
  }//GEN-LAST:event_girarHorarioActionPerformed

  private void girarAntiHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girarAntiHorarioActionPerformed
    comandoAtual = "ga";
    executar();
  }//GEN-LAST:event_girarAntiHorarioActionPerformed

  private void botaoDireita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDireita1ActionPerformed
    comandoAtual = "rd";
    executar();

  }//GEN-LAST:event_botaoDireita1ActionPerformed

  private void botaoDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDireitaActionPerformed
    comandoAtual = "direita";
    executar();
  }//GEN-LAST:event_botaoDireitaActionPerformed

  private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
    // TODO add your handling code here:
    new Updater(this).start();
  }//GEN-LAST:event_botaoAtualizarActionPerformed

  private void sliderServoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderServoStateChanged
    // TODO add your handling code here:
    //DevBotSerial.robot.servo(sliderServo.getValue());
  }//GEN-LAST:event_sliderServoStateChanged

  private void botaoServoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoServoActionPerformed
    // TODO add your handling code here:
    try {
      robot.send("servo?" + sliderServo.getValue());
    } catch (IOException ex) {
      Logger.getLogger(DevBotWindow.class.getName()).log(Level.SEVERE, null, ex);
    }

  }//GEN-LAST:event_botaoServoActionPerformed
  class Updater extends Thread {

    DevBotWindow console;

    Updater(DevBotWindow dev) {
      this.console = dev;
    }

    public void run() {
      while (Integer.parseInt(console.tempoSensorLuz.getText()) > 0) {
        try {
          double temperaturaOrigem = 0;
          try {
            //temperaturaOrigem = DevBotSerial.robot.sensorTemperatura();
            robot.sensorTemperatura();
            temperaturaOrigem = robot.sensorTemperatura;
            double temperatura = (temperaturaOrigem * 0.00488);
            temperatura *= 100;
            console.temperatura.setText("" + (formatadorTemperatura.format(temperatura)) + " c");

          } catch (Exception e) {
            System.out.println("Erro lendo sensor de temperatura. Dado inválido.");
          }
          try {
            robot.sensorLuz();
            int luz = robot.sensorLuz;
            console.sensorLuz.setText("" + luz);
            console.sliderSensorLuz.setValue(luz);
          } catch (Exception e) {
            System.out.println("Erro lendo sensor de luz. Dado inválido.");
          }
          try {
            robot.sensorDistancia1();
            int dist = robot.sensorDistancia1;
            console.distancia.setText("Distância: " + dist + " cm");
          } catch (Exception e) {
            System.out.println("Erro lendo sensor de luz. Dado inválido.");
          }
        } catch (Exception ex) {
          Logger.getLogger(DevBotWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
          Thread.sleep(1000 / Integer.parseInt(console.tempoSensorLuz.getText()));
        } catch (InterruptedException ex) {
          Logger.getLogger(DevBotWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoDireita;
    private javax.swing.JButton botaoDireita1;
    private javax.swing.JButton botaoEsquerda;
    private javax.swing.JButton botaoEsquerda1;
    private javax.swing.JButton botaoFrente;
    private javax.swing.JButton botaoParar;
    private javax.swing.JButton botaoRe;
    private javax.swing.JButton botaoServo;
    private javax.swing.JLabel distancia;
    private javax.swing.JButton girarAntiHorario;
    private javax.swing.JButton girarHorario;
    private javax.swing.JSlider intensidade;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel painelSensorLuz;
    private javax.swing.JTextField sensorLuz;
    private javax.swing.JSlider sliderSensorLuz;
    private javax.swing.JSlider sliderServo;
    private javax.swing.JLabel temperatura;
    private javax.swing.JTextField tempoSensorLuz;
    private javax.swing.JToggleButton todosRobots;
    // End of variables declaration//GEN-END:variables
}
